[tool.poetry]
name = "avesrag-dataset-builder"
version = "0.1.0"
description = "Pipeline de construção de dataset para o AvesRAG"
authors = []
packages = [{include = "scr"}]

[tool.poetry.dependencies]
python = "^3.13"
pandas = "*"
pymongo = "*"
psycopg2-binary = "*"
python-dotenv = "*"
openpyxl = "^3.1.5"
playwright = "^1.60.0"
beautifulsoup4 = "^4.15.0"
rapidfuzz = "^3.14.5"
tqdm = "^4.68.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
